# -*- coding: utf-8 -*-
"""Customer Behaviour Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SbARJ8_c719HB4fVsAhfuehQx72FR7OV
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df=pd.read_csv("ecommerce_customer_data.csv")
df.head() #view dataset

df.describe() #numeric summary

#categorical_summary
df.describe(include='object')

#checking null values
df.isnull().sum()

#check the distribution of 'Age' in dataset
fig=px.histogram(df,x='Age',title='Distribution of Age',nbins=20,color_discrete_sequence=['skyblue'])
fig.show()

df['Gender'].value_counts() #gender counts

"""**Lets Check cor-relation**"""

df.corr(numeric_only=True)

"""**Analyzing Customer Behaviour**

> Now, let’s have a look at the relationship between the product browsing time and the total pages viewed:


"""

fig=px.scatter(df,x='Product_Browsing_Time',y='Total_Pages_Viewed',title='Browsing Time VS Total Pages Viewed',trendline='ols')
fig.show()

"""**The above scatter plot shows no consistent pattern or strong association between the time spent browsing products and the total number of pages viewed. It indicates that customers are not necessarily exploring more pages if they spend more time on the website, which might be due to various factors such as the website design, content relevance, or individual user preferences.**"""





import plotly.express as px

# Assuming df is your DataFrame
gender_grouped = df.groupby('Gender').agg({'Items_Added_to_Cart': 'mean', 'Total_Purchases': 'mean'}).reset_index()
gender_grouped.columns = ['Gender', 'Average_Items_Added_to_Cart', 'Average_Purchase']

fig = px.bar(gender_grouped, x='Gender', y=['Average_Items_Added_to_Cart', 'Average_Purchase'],
             title='Average Items Added to Cart and Purchase by Gender',
             labels={'value': 'Average', 'variable': 'Metric', 'Gender': 'Gender'},
             color_discrete_sequence=['skyblue', 'orange'],
             barmode='group')

fig.update_layout(xaxis_title='Gender', yaxis_title='Average', legend_title='Metric')

fig.show()
print(gender_grouped)

"""Shopping Behavior by Gender:

Females, on average, add 5.27 items to their carts, suggesting exploratory shopping.
Males average 5.04 items, indicating a more focused approach.
Females spend an average of $2.28 per transaction, while males spend $2.64.
Understanding these gender-specific patterns enables tailored marketing strategies. **bold text**
"""

# Grouped Analysis
gender_grouped = df.groupby('Gender')['Total_Pages_Viewed'].mean().reset_index()
gender_grouped.columns = ['Gender', 'Average_Total_Pages_Viewed']
fig = px.bar(gender_grouped, x='Gender', y='Average_Total_Pages_Viewed',title='Average Total Pages Viewed by Gender')
fig.show()

#Now, let’s have a look at the average total pages viewed by devices
devices_grouped = df.groupby('Device_Type')['Total_Pages_Viewed'].mean().reset_index()
devices_grouped.columns = ['Device_Type', 'Average_Total_Pages_Viewed']
fig = px.bar(devices_grouped, x='Device_Type', y='Average_Total_Pages_Viewed',
             title='Average Total Pages Viewed by Devices')
fig.show()

"""**Now, let’s calculate the customer lifetime value and visualize segments based on the customer lifetime value:**"""

df['CLV'] = (df['Total_Purchases'] * df['Total_Pages_Viewed']) / df['Age']
df.head()

df['Segment'] = pd.cut(df['CLV'], bins=[1, 2.5, 5, float('inf')],
                         labels=['Low Value', 'Medium Value', 'High Value'])

segment_counts = df['Segment'].value_counts().reset_index()
segment_counts.columns = ['Segment', 'Count']

# Create a bar chart to visualize the customer segments
fig = px.bar(segment_counts, x='Segment', y='Count',
             title='Customer Segmentation by CLV')
fig.update_xaxes(title='Segment')
fig.update_yaxes(title='Number of Customers')
fig.show()

# Funnel analysis
funnel_data = df[['Product_Browsing_Time', 'Items_Added_to_Cart', 'Total_Purchases']]
funnel_data = funnel_data.groupby(['Product_Browsing_Time', 'Items_Added_to_Cart']).sum().reset_index()

fig = px.funnel(funnel_data, x='Product_Browsing_Time', y='Items_Added_to_Cart', title='Conversion Funnel')
fig.show()

"""**In the above graph, the x-axis represents the time customers spend browsing products on the e-commerce platform. The y-axis represents the number of items added to the shopping cart by customers during their browsing sessions.**"""

#Now, let’s have a look at the churn rate of the customers:
df['Churned']=df['Total_Purchases']==0
churn_rate=df['Churned'].mean()
print(churn_rate)

"""**A churn rate of 0.198 indicates that a significant portion of customers has churned, and addressing this churn is important for maintaining business growth and profitability.**

**Summary**
*Customer Behavior Analysis is a process that involves examining and understanding how customers interact with a business, product, or service. This analysis helps organizations make informed decisions, tailor their strategies, and enhance customer experiences*
"""

